[expressions.steel_cables]
width = 2500
height = 2500
depth = 16
generate = "0xff x * t y - & dup * abs t >> 0xf0f /"
farbfeld_hash = { blake3 = "65f48f6907e2e1b94c82c2c0fe5554f300984f57c8006cec6837559ee0c335de" }

[expressions.edgy]
width = 2500
height = 2500
depth = 1
generate = "w y * x + dup t % t ^ /"
farbfeld_hash = { blake3 = "5a91745beaf5970b7988dd236cae1129b9c1848a3994e7c2d04860a4bd3cdbed" }

[expressions.eye_fucker]
width = 1200
height = 1200
depth = 16
generate = "x y - y x - * x y & - dup 2 * t + -"
farbfeld_hash = { blake3 = "d4f8f6c4cdfc095e5db1d4daa042b4828a4b359b1804ba344b4b063737d0d1a3" }

[expressions.runaway]
width = 500
height = 500
depth = 1
generate = "t w || x w - || h t << h y >> && << w x >> y x <= < t abs y x * = <= >> abs"
farbfeld_hash = { blake3 = "0f93e4d50f4af0ca19c85036bdc8de00ea988698df7f7d3551a5faa190ebf406" }

[expressions.life_of_pi]
width = 500
height = 500
depth = 1
generate = "x t | x ! | abs h x ^ y x + < y w / w x * >> << * t y + w t << ^ t t & t t + & >> y h < t ~ || x h << ! | <= ^"
farbfeld_hash = { blake3 = "2b299b601f41b0a05157fd35a7316628c294444950ef3bd3bdf26d25f413f954" }

[expressions.prison_cell]
width = 500
height = 500
depth = 1
generate = "y ! h h * | w w ^ y t = << >= x w | h x | << y w <= w h - ^ * <= h w | abs x abs abs ^ y t - t y / <= w x >> x w >= << < - +"
farbfeld_hash = { blake3 = "c7f03380a206c2b6679348fb0828edbc746f0ff251c6c22517a5c4faf99ba0d4" }

[expressions.grim]
width = 500
height = 500
depth = 1
generate = "h w / w h = || x y && w t & - && t h ^ t w + << w h / w h | = % * y h + x t < ^ ~ ~ >>"
farbfeld_hash = { blake3 = "fe66a0c73759882b456c6c3ddd93706d431be6c44087ca186f3124edb7ed497e" }

[expressions.techno]
width = 500
height = 500
depth = 1
generate = "x y && y h - < x h && ! >= w ! x w <= * t t - t h << && && || w x / w x & <= w t % t t << / & x t >= y t >> - h t << x ! * < || &&"
farbfeld_hash = { blake3 = "9a3dfd98286b3bd6eb7de5639a5acf7682c6b64f7feec3c7bb65af0cb40bc2ad" }
