[package]
name = "feim"
version = "0.2.0"
authors = ["Tiago Carvalho <sugoiuguu@tfwno.gf>"]
edition = "2018"

[features]
default = ["fmt-farbfeld"]
fmt-jpeg = ["jpeg-decoder"]
fmt-farbfeld = []

[dependencies]
jpeg-decoder = { version = "0.1", optional = true }
