[package]
name = "resize"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
resize_img = { package = "resize", version = "0.7" }
feim = { path = "../../crate", features = ["fmt-farbfeld"] }
